import type { StudentInput } from '@/types';

export const SAMPLE_STUDENTS: StudentInput[] = [
  { student_id: 'STU001', name: 'Aarav Sharma', gender: 'Male', age: 19, attendance: 92, assignment_score: 88, internal_marks: 85, previous_marks: 82, study_hours: 28, final_marks: 89 },
  { student_id: 'STU002', name: 'Priya Patel', gender: 'Female', age: 18, attendance: 95, assignment_score: 92, internal_marks: 90, previous_marks: 88, study_hours: 35, final_marks: 94 },
  { student_id: 'STU003', name: 'Rahul Verma', gender: 'Male', age: 20, attendance: 68, assignment_score: 55, internal_marks: 48, previous_marks: 52, study_hours: 12, final_marks: 42 },
  { student_id: 'STU004', name: 'Sneha Reddy', gender: 'Female', age: 19, attendance: 88, assignment_score: 78, internal_marks: 75, previous_marks: 72, study_hours: 22, final_marks: 79 },
  { student_id: 'STU005', name: 'Karthik Nair', gender: 'Male', age: 21, attendance: 75, assignment_score: 65, internal_marks: 60, previous_marks: 58, study_hours: 15, final_marks: 63 },
  { student_id: 'STU006', name: 'Ananya Gupta', gender: 'Female', age: 18, attendance: 97, assignment_score: 95, internal_marks: 93, previous_marks: 91, study_hours: 38, final_marks: 96 },
  { student_id: 'STU007', name: 'Vikram Singh', gender: 'Male', age: 20, attendance: 60, assignment_score: 45, internal_marks: 40, previous_marks: 48, study_hours: 8, final_marks: 38 },
  { student_id: 'STU008', name: 'Divya Iyer', gender: 'Female', age: 19, attendance: 85, assignment_score: 82, internal_marks: 78, previous_marks: 76, study_hours: 25, final_marks: 83 },
  { student_id: 'STU009', name: 'Arjun Kumar', gender: 'Male', age: 22, attendance: 78, assignment_score: 70, internal_marks: 68, previous_marks: 65, study_hours: 18, final_marks: 71 },
  { student_id: 'STU010', name: 'Meera Joshi', gender: 'Female', age: 18, attendance: 90, assignment_score: 85, internal_marks: 82, previous_marks: 80, study_hours: 30, final_marks: 86 },
  { student_id: 'STU011', name: 'Rohan Das', gender: 'Male', age: 19, attendance: 72, assignment_score: 58, internal_marks: 55, previous_marks: 50, study_hours: 10, final_marks: 48 },
  { student_id: 'STU012', name: 'Kavya Rao', gender: 'Female', age: 20, attendance: 94, assignment_score: 90, internal_marks: 88, previous_marks: 85, study_hours: 32, final_marks: 91 },
  { student_id: 'STU013', name: 'Aditya Menon', gender: 'Male', age: 21, attendance: 82, assignment_score: 75, internal_marks: 72, previous_marks: 70, study_hours: 20, final_marks: 76 },
  { student_id: 'STU014', name: 'Pooja Bhat', gender: 'Female', age: 19, attendance: 65, assignment_score: 50, internal_marks: 45, previous_marks: 55, study_hours: 9, final_marks: 44 },
  { student_id: 'STU015', name: 'Siddharth Roy', gender: 'Male', age: 18, attendance: 87, assignment_score: 80, internal_marks: 77, previous_marks: 74, study_hours: 24, final_marks: 81 },
  { student_id: 'STU016', name: 'Ishita Agarwal', gender: 'Female', age: 20, attendance: 91, assignment_score: 87, internal_marks: 84, previous_marks: 81, study_hours: 27, final_marks: 88 },
  { student_id: 'STU017', name: 'Nikhil Pillai', gender: 'Male', age: 22, attendance: 55, assignment_score: 40, internal_marks: 35, previous_marks: 42, study_hours: 6, final_marks: 35 },
  { student_id: 'STU018', name: 'Tanvi Desai', gender: 'Female', age: 19, attendance: 83, assignment_score: 76, internal_marks: 73, previous_marks: 71, study_hours: 21, final_marks: 77 },
  { student_id: 'STU019', name: 'Manish Yadav', gender: 'Male', age: 20, attendance: 76, assignment_score: 68, internal_marks: 62, previous_marks: 60, study_hours: 14, final_marks: 66 },
  { student_id: 'STU020', name: 'Ritu Malhotra', gender: 'Female', age: 18, attendance: 96, assignment_score: 93, internal_marks: 91, previous_marks: 89, study_hours: 36, final_marks: 95 },
  { student_id: 'STU021', name: 'Gaurav Saxena', gender: 'Male', age: 21, attendance: 70, assignment_score: 60, internal_marks: 57, previous_marks: 54, study_hours: 11, final_marks: 56 },
  { student_id: 'STU022', name: 'Nisha Kulkarni', gender: 'Female', age: 19, attendance: 89, assignment_score: 83, internal_marks: 80, previous_marks: 78, study_hours: 26, final_marks: 84 },
  { student_id: 'STU023', name: 'Varun Chatterjee', gender: 'Male', age: 20, attendance: 80, assignment_score: 72, internal_marks: 69, previous_marks: 67, study_hours: 19, final_marks: 73 },
  { student_id: 'STU024', name: 'Shruti Pandey', gender: 'Female', age: 18, attendance: 93, assignment_score: 89, internal_marks: 86, previous_marks: 83, study_hours: 33, final_marks: 90 },
  { student_id: 'STU025', name: 'Akash Mishra', gender: 'Male', age: 22, attendance: 62, assignment_score: 48, internal_marks: 43, previous_marks: 46, study_hours: 7, final_marks: 41 },
  { student_id: 'STU026', name: 'Riya Banerjee', gender: 'Female', age: 19, attendance: 86, assignment_score: 79, internal_marks: 76, previous_marks: 73, study_hours: 23, final_marks: 80 },
  { student_id: 'STU027', name: 'Saurabh Jain', gender: 'Male', age: 20, attendance: 74, assignment_score: 66, internal_marks: 61, previous_marks: 59, study_hours: 13, final_marks: 64 },
  { student_id: 'STU028', name: 'Anika Bose', gender: 'Female', age: 18, attendance: 98, assignment_score: 94, internal_marks: 92, previous_marks: 90, study_hours: 40, final_marks: 97 },
  { student_id: 'STU029', name: 'Yashwant Reddy', gender: 'Male', age: 21, attendance: 67, assignment_score: 52, internal_marks: 47, previous_marks: 51, study_hours: 9, final_marks: 46 },
  { student_id: 'STU030', name: 'Lakshmi Krishnan', gender: 'Female', age: 19, attendance: 84, assignment_score: 77, internal_marks: 74, previous_marks: 72, study_hours: 22, final_marks: 78 },
  { student_id: 'STU031', name: 'Devesh Trivedi', gender: 'Male', age: 20, attendance: 79, assignment_score: 71, internal_marks: 66, previous_marks: 63, study_hours: 17, final_marks: 69 },
  { student_id: 'STU032', name: 'Sakshi Shetty', gender: 'Female', age: 18, attendance: 90, assignment_score: 86, internal_marks: 83, previous_marks: 81, study_hours: 29, final_marks: 87 },
];
